[project]
name = "xscreenrecordreceiver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy==1.24.3",
    "opencv-python==4.8.1.78",
    "websockets==11.0.3",
]
